LEFT:
  arm_id: "fr3"
  arm_prefix: "left"
  controller_cpus: "8-9"
  fake_sensor_commands: "false"
  namespace: "left"
  robot_ip: "172.16.26.5"
  urdf_file: "fr3/fr3.urdf.xacro"
  use_fake_hardware: "false"

RIGHT:
  arm_id: "fr3"
  arm_prefix: "right"
  controller_cpus: "12-13"
  fake_sensor_commands: "false"
  namespace: "right"
  robot_ip: "172.16.26.4"
  urdf_file: "fr3/fr3.urdf.xacro"
  use_fake_hardware: "false"
